### ISSUE TITLE
Addon Issues SS (Honeyback Hive)

### ISSUE THREAD

**Issue by halloaloe** [pontusm/ReputationBars#1]
Glad to finally get these to you. Hope they help. Please reply to the comment on Curse if you have any other questions.

![Static Bars Honeyback Hive](https://user-images.githubusercontent.com/97870794/156640454-95b354e3-df95-499f-a399-a9f0610e0020.jpg)
![Static Settings BfA](https://user-images.githubusercontent.com/97870794/156640564-141093fb-d1eb-4468-82e2-4066d63e60b5.jpg)
![General Settings](https://user-images.githubusercontent.com/97870794/156640585-23d8aedb-c3f8-47e1-9a32-1e90be4bbae3.jpg)
![Static Settings Inactive](https://user-images.githubusercontent.com/97870794/156640639-6e2426f3-df4e-445b-84a2-0e98ddc6113d.jpg)
![Rep BfA](https://user-images.githubusercontent.com/97870794/156640654-0e3bb180-0af8-40f8-bf02-8fbcfa268d3d.jpg)

These are all the reps that I've maxed out and turned inactive. I assume they are below the "sill" in the addon:

![Inactive 1](https://user-images.githubusercontent.com/97870794/156640777-e5ccaf20-95cd-45d9-9e8b-cd27f239ef13.jpg)
![Inactive 2](https://user-images.githubusercontent.com/97870794/156640906-a33f836a-49b3-4e1a-8d33-e5f57579727e.jpg)
![Inactive 3](https://user-images.githubusercontent.com/97870794/156640925-04c79a82-ef09-48a9-b632-ae2b605e1b64.jpg)
![Inactive 4](https://user-images.githubusercontent.com/97870794/156640942-edc5b09a-f81f-4229-88f3-d6251b7c511a.jpg)
![Inactive 5](https://user-images.githubusercontent.com/97870794/156640957-b31408b3-2b1c-45a7-9aaa-ca7a93d4d109.jpg)
![Inactive 6](https://user-images.githubusercontent.com/97870794/156640972-ebb96d31-88c4-44a0-a8c0-6db5a43387e8.jpg)

**Comment by karpana** [comment]
Thank you for this issue @halloaloe.

While I'm not sure how to quite fix Reputation Bars just yet....
I think I might have a workaround for you...

1) In the character reputation screen ... [Character Info (C) -> Reputation Tab]
2) locate the "Honeyback Hive" reputation (In the inactive area)
3) Left-Click on the reputation (bringing up a small side bar)
4) Deselect "Move To Inactive"

(This will put it back up top with the other BFA reputations)

Next, go into ReputationBars settings, and under BFA, you should now be able to deselect it and remove it from your static bar

If you want it to be back in the "inactive area" of the character reputation info screen, redo steps 1 to 4 above (looking for Honeyback Hive in the BFA area).

Let me know how this goes.

**Comment by halloaloe** [comment]
*facepalm*
Yeah, that fixed it. I should have realized that myself, honestly. I sometimes get overzealous about moving reps to inactive before unselecting them in RepBars. Thanks.

Does my SS about the Inactive section needing a scrollbar make sense now? I'm always worried I don't describe it well enough. Is it possible?

**Comment by karpana** [comment]
Glad we got that resolved for you @halloaloe.

I'm going to close this item for now ... but will look at how to incorporate the scroll bar that you recommended.
