### ISSUE TITLE
WatchBar module error

### ISSUE THREAD

**Issue by EKE00372** [pontusm/ReputationBars#5]
`Interface/AddOns/ReputationBars/Modules/WatchBar.lua:299: attempt to index global 'ReputationWatchBar' (a nil value)`

I've do a new install without any other addon and get this error.

I think `ReputationWatchBar` already renamed as `StatusTrackingBarManager`.......?

**Comment by karpana** [comment]
Not able to determine the issue, as I've never used the module to know what it's supposed to do.
